### ISSUE TITLE
PlasmaChain connection error during withdrawal from extdev resulted in token stuck in rinkeby gateway contract 

### ISSUE THREAD

**Issue by cartosys** [loomnetwork/truffle-dappchain-example#10]
This occurred while stepping through the tutorial at https://loomx.io/developers/docs/en/extdev-transfer-gateway.html 

When I got to this step:

>  ./gateway-cli.js withdraw-token 1

The following error resulted: 
"PlasmaChain connection error" 
See full error output at the end of post.

Now I run this and see only 2 tokens on rinkeby:
`node ./gateway-cli.js token-balance -c eth`
Results: 0xaA250e148DFa344E8D266B0F011De400b433793D owns 2 tokens.

0 tokens on extdev
`node ./gateway-cli.js token-balance` 
Results: 0xc47d63f844416059eb0e2bead69c46aea2dfd559 owns 0 tokens.

And 1 token in gateway:
`node ./gateway-cli.js token-balance -a gateway -c eth`

Results: 0x6f7Eb868b2236638c563af71612c9701AC30A388 owns 1 tokens.
First 1 token(s): 1

Note that I've since minted a 4th token on my rinkeby address so that address now shows 3 tokens but 1 still remains stuck in the gateway contract.

Full Errors produced by `node ./gateway-cli.js withdraw-token 1`:

```
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/queryws',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/websocket',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/queryws',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/websocket',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/queryws',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/websocket',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/queryws',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/websocket',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/queryws',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
PlasmaChain connection error { kind: 'error',
  url: 'wss://extdev-plasma-us1.dappchains.com/websocket',
  error: Error: Unexpected server response: 521
    at ClientRequest.req.on (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/ws/lib/websocket.js:542:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) }
Error: Timeout while waiting for withdrawal to be signed
    at Timeout.setTimeout [as _onTimeout] (/home/ubuntu/token-game/truffle-dappchain-example/gateway-cli.js:224:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

**Comment by cartosys** [comment]
Also I'm unable to perform any other further withdrawals (even using the ERC20 example functions):

> node ./gateway-cli.js withdraw-coin 60

Error: Failed to commit Tx: TG003: pending withdrawal already exists
    at Client.<anonymous> (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/loom-js/dist/client.js:205:39)
    at step (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/home/ubuntu/token-game/truffle-dappchain-example/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:13552) UnhandledPromiseRejectionWarning: Error: Timeout while waiting for withdrawal to be signed
    at Timeout.setTimeout [as _onTimeout] (/home/ubuntu/token-game/truffle-dappchain-example/gateway-cli.js:180:20)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:13552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by enlight** [comment]
Have you tried running the `resume-withdrawal` command mentioned in the troubleshooting section? https://loomx.io/developers/docs/en/extdev-transfer-gateway.html#troubleshooting

**Comment by cartosys** [comment]
Ahh, yes. i saw that earlier but it slipped my mind. Thank you!

**Comment by enlight** [comment]
Closing since the issue has been resolved.
