### ISSUE TITLE
Error when running "yarn gen:rinkeby-key" while following Transfer Gateway Testnet Tutorial

### ISSUE THREAD

**Issue by cryptoraves** [loomnetwork/truffle-dappchain-example#40]
`$ node ./scripts/gen-eth-key.js rinkeby
internal/crypto/hash.js:58
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type object
    at Hmac.update (internal/crypto/hash.js:58:11)
    at Function.HDKey.fromMasterSeed (/home/cartosys/www/truffle-dappchain-example/node_modules/hdkey/lib/hdkey.js:177:54)
    at Function.EthereumHDKey.fromMasterSeed (/home/cartosys/www/truffle-dappchain-example/node_modules/ethereumjs-wallet/hdkey.js:18:26)
    at Object.<anonymous> (/home/cartosys/www/truffle-dappchain-example/scripts/gen-eth-key.js:26:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Replacing line 26 in scripts/gen-eth-key.js works.  change from: 

`const hdwallet = hdkey.fromMasterSeed(bip39.mnemonicToSeed(mnemonic))`

To:

`const hdwallet = hdkey.fromMasterSeed(mnemonic)`

Fixes it.

Fresh Ubuntu 18.04 install
Yarn 1.17.3
Node 10.15.3

**Comment by andreipope** [comment]
@cryptoraves Looks like `mnemonicToSeed` is an asynchronous function now. Probably it's a recent change. Does this work for you:
```

**Comment by cryptoraves** [comment]
All good now! Thx
