### ISSUE TITLE
could not deploy to ExtDev Testnet 

### ISSUE THREAD

**Issue by babo105** [loomnetwork/truffle-dappchain-example#56]
Dear Team,

I tried to run the example from the beginning as shows in the documentation.
First, I hade to change the Truffle configuration as:
`  compilers: {
    solc: {
      version: '^0.5.0',
      settings: {
        optimizer: {
          enabled: true,
          runs: 200
        },
        evmVersion: "constantinople"
      }
    }
  },`

But then I got an error if i run this:

`truffle deploy --network extdev_plasma_us1`

The output and the error:
`Compiling your contracts...`
`===========================`
``
`√ Fetching solc version list from solc-bin. Attempt #1`
`> Everything is up to date, there is nothing to compile.`
``
`> Something went wrong while attempting to connect to the network. Check your network configuration.`
`Error: Request failed with status code 521`
`    at createError (x:\github\truffle-dappchain-example\node_modules\axios\lib\core\createError.js:16:15)`
`    at settle (x:\github\truffle-dappchain-example\node_modules\axios\lib\core\settle.js:18:12)`
`    at IncomingMessage.handleStreamEnd (x:\github\truffle-dappchain-example\node_modules\axios\lib\adapters\http.js:202:11)`
`    at IncomingMessage.emit (events.js:327:22)`
`    at endReadableNT (internal/streams/readable.js:1327:12)`
`    at processTicksAndRejections (internal/process/task_queues.js:80:21)`
`Truffle v5.3.1 (core: 5.3.1)`
`Node v14.16.0`

My network is OK tried multiple Internet connections.
If I check the 'http://extdev-plasma-us1.dappchains.com:80/query' URL, it is wrong, the WS URL is okay, just the HTTP URL is wrong or not working.

Could you help or fix the example to work?

Many thanks!

**Comment by babo105** [comment]
After talking with the team, found out that the ExtDev chan was down, they fixed. Now works like a charm. However I needed to change few configurations to run properly on Windows 10, see my original post.
