### ISSUE TITLE
Error Running Truffle Unbox

### ISSUE THREAD

**Issue by pynchmeister** [loomnetwork/truffle-dappchain-example#6]
`truffle unbox loomnetwork/truffle-dappchain-example` throws an error: 

Error: Truffle Box at URL https://github.com/loomnetwork/truffle-dappchain-example doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

I followed all the instructions, is anyone aware of a solution?

**Comment by eduardonunesp** [comment]
The issue https://github.com/trufflesuite/truffle/issues/1309 should be fixed probably isn't published yet on npm with a the new version, I believe the version 4.1.15 should solve

**Comment by pynchmeister** [comment]
ok thanks, feel free to close this issue
